sonar.projectKey=Ah-med-Yahia_xBrain
sonar.organization=ah-med-yahia
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*_test.dart
sonar.coverageReportPaths=coverage/sonar-generic-coverage.xml

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/.dart_tool/**,**/build/**,**/ios/**,**/android/**,**/linux/**,**/macos/**,**/windows/**,**/web/**